In [47]:
#import libraries
import pandas as pd
import numpy as np

In [48]:
#number of samples
n = 5000

#create empty arrays to fill data
death_time, host_bld, level, phase, wflw_atk, hp_pct, lctn, phtm_cnt, phtm_bld, phtm_dth  = np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n), np.zeros(n)

## Host Death - How long the host managed to live in seconds.
for i in range(n):
  death_time[i] = np.random.randint(10,301)

## Host Build - The build of the host - RAW_CAST, MELEE_PROC, RAW_PROC, RAW_MELEE, HYBRID
for i in range(n):
  host_bld[i] = np.random.randint(1,6)

## Level - Levels 120 to 180
for i in range(n):
  level[i] = np.random.randint(120,181)

## Phase - Phase 1 or Phase 2 of the boss
for i in range(n):
  phase[i] = np.random.randint(1,3)

## Waterflow Death - 0 if not death by Waterflow, 1 if death by Waterflow
for i in range(n):
  wflw_atk[i] = np.random.randint(0,2)

## Health Percentage - Percentage of HP left by boss -- from 6% to 93%
for i in range(n):
  hp_pct[i] = np.random.randint(6,94)

## Location of Death - Where the host died - CENTER, CORNER, OTHER
for i in range(n):
  lctn[i] = np.random.randint(1,4)

## Phantom Count - 1 or 2 Phantoms, will always have at least 1 phantom due to my presence
for i in range(n):
  phtm_cnt[i] = np.random.randint(1,3)

## Phantom Build - If there is another phantom what is their build
for i in range(n):
  phtm_bld[i] = np.random.randint(1,6)

## Phantom Death - Did the other phantom die before the host? - 0 or 1
for i in range(n):
  phtm_dth[i] = np.random.randint(0,2)

In [49]:
## Placing in Data Frame

df = pd.DataFrame(death_time, columns=['Host_Death_Time'])

df.head()

   Host_Death_Time
0            147.0
1            102.0
2             81.0
3             73.0
4            141.0

In [50]:
#Adding in remaining columns
df['Host_Build'] = host_bld
df['Level'] = level
df['Phase'] = phase
df['Waterflow_Death'] = wflw_atk
df['Health_Pct'] = hp_pct
df['Location'] = lctn
df['Phantom_Count'] = phtm_cnt
df['Phantom_Build'] = phtm_bld
df['Phantom_Death'] = phtm_dth

df.head(25)

,Host_Death_Time,Host_Build,Level,Phase,Waterflow_Death,Health_Pct,Location,Phantom_Count,Phantom_Build,Phantom_Death
0,147.0,5.0,149.0,1.0,1.0,25.0,1.0,2.0,5.0,0.0
1,102.0,1.0,164.0,1.0,1.0,66.0,2.0,1.0,2.0,1.0
2,81.0,3.0,146.0,1.0,1.0,30.0,1.0,2.0,2.0,1.0
3,73.0,5.0,154.0,2.0,0.0,65.0,1.0,1.0,5.0,1.0
4,141.0,4.0,146.0,1.0,1.0,6.0,1.0,1.0,1.0,1.0
5,169.0,5.0,140.0,1.0,1.0,89.0,1.0,2.0,1.0,0.0
6,292.0,1.0,159.0,1.0,1.0,62.0,2.0,2.0,2.0,1.0
7,148.0,1.0,176.0,1.0,0.0,11.0,1.0,1.0,1.0,1.0
8,193.0,5.0,177.0,2.0,1.0,29.0,3.0,1.0,4.0,1.0
9,274.0,4.0,162.0,2.0,1.0,11.0,1.0,1.0,4.0,0.0
10,156.0,4.0,150.0,1.0,1.0,58.0,1.0,1.0,4.0,0.0
11,117.0,4.0,141.0,1.0,0.0,89.0,1.0,2.0,5.0,0.0
12,283.0,4.0,154.0,1.0,0.0,14.0,1.0,2.0,2.0,0.0
13,95.0,2.0,173.0,2.0,0.0,26.0,2.0,1.0,1.0,1.0
14,159.0,2.0,150.0,2.0,0.0,43.0,1.0,2.0,4.0,0.0
15,132.0,5.0,121.0,1.0,1.0,43.0,2.0,1.0,4.0,0.0
16,236.0,4.0,152.0,1.0,0.0,54.0,3.0,2.0,1.0,1.0
17,160.0,2.0,150.0,2.0,1.0,55.0,2.0,1.0,2.0,0.0
18,27.0,4.0,160.0,2.0,0.0,28.0,3.0,1.0,2.0,0.0
19,156.0,1.0,164.0,2.0,0.0,53.0,3.0,1.0,4.0,1.0
20,77.0,2.0,151.0,1.0,1.0,55.0,3.0,2.0,4.0,0.0
21,20.0,2.0,151.0,2.0,0.0,76.0,1.0,2.0,5.0,0.0
22,239.0,5.0,173.0,2.0,0.0,58.0,1.0,2.0,5.0,0.0
23,48.0,3.0,129.0,1.0,1.0,36.0,1.0,1.0,1.0,1.0
24,210.0,3.0,138.0,1.0,0.0,56.0,2.0,1.0,4.0,0.0

In [51]:
## Summary statistics
df.describe

<bound method NDFrame.describe of       Host_Death_Time  Host_Build  Level  Phase  Waterflow_Death  Health_Pct  \
0               147.0         5.0  149.0    1.0              1.0        25.0
1               102.0         1.0  164.0    1.0              1.0        66.0
2                81.0         3.0  146.0    1.0              1.0        30.0
3                73.0         5.0  154.0    2.0              0.0        65.0
4               141.0         4.0  146.0    1.0              1.0         6.0
...               ...         ...    ...    ...              ...         ...
4995            225.0         5.0  180.0    2.0              1.0        54.0
4996             32.0         5.0  149.0    1.0              1.0        67.0
4997            239.0         5.0  139.0    2.0              1.0         9.0
4998             57.0         2.0  147.0    1.0              1.0        79.0
4999            101.0         5.0  170.0    2.0              1.0        62.0

      Location  Phantom_Count  Phantom_Build  Phantom_Death
0          1.0            2.0            5.0            0.0
1          2.0            1.0            2.0            1.0
2          1.0            2.0            2.0            1.0
3          1.0            1.0            5.0            1.0
4          1.0            1.0            1.0            1.0
...        ...            ...            ...            ...
4995       1.0            2.0            5.0            1.0
4996       3.0            2.0            2.0            0.0
4997       1.0            2.0            2.0            0.0
4998       3.0            2.0            4.0            0.0
4999       1.0            1.0            5.0            0.0

[5000 rows x 10 columns]>

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Host_Death_Time  5000 non-null   float64
 1   Host_Build       5000 non-null   float64
 2   Level            5000 non-null   float64
 3   Phase            5000 non-null   float64
 4   Waterflow_Death  5000 non-null   float64
 5   Health_Pct       5000 non-null   float64
 6   Location         5000 non-null   float64
 7   Phantom_Count    5000 non-null   float64
 8   Phantom_Build    5000 non-null   float64
 9   Phantom_Death    5000 non-null   float64
dtypes: float64(10)
memory usage: 390.8 KB

In [53]:
# For a control on realistic information, drop rows where Health_Pct is less than 75 and HDT is less than 30 seconds
# This is to prevent unrealistic information, where it takes time for the host to die and cross the arena
# and for Malenia to not be damaged so quickly in a manner that could not happen

df2 = df[(df['Host_Death_Time'] < 31) & (df['Health_Pct'] < 75) ]
df = df[~df.index.isin(df2.index)]
df.head(10)

,Host_Death_Time,Host_Build,Level,Phase,Waterflow_Death,Health_Pct,Location,Phantom_Count,Phantom_Build,Phantom_Death
0,147.0,5.0,149.0,1.0,1.0,25.0,1.0,2.0,5.0,0.0
1,102.0,1.0,164.0,1.0,1.0,66.0,2.0,1.0,2.0,1.0
2,81.0,3.0,146.0,1.0,1.0,30.0,1.0,2.0,2.0,1.0
3,73.0,5.0,154.0,2.0,0.0,65.0,1.0,1.0,5.0,1.0
4,141.0,4.0,146.0,1.0,1.0,6.0,1.0,1.0,1.0,1.0
5,169.0,5.0,140.0,1.0,1.0,89.0,1.0,2.0,1.0,0.0
6,292.0,1.0,159.0,1.0,1.0,62.0,2.0,2.0,2.0,1.0
7,148.0,1.0,176.0,1.0,0.0,11.0,1.0,1.0,1.0,1.0
8,193.0,5.0,177.0,2.0,1.0,29.0,3.0,1.0,4.0,1.0
9,274.0,4.0,162.0,2.0,1.0,11.0,1.0,1.0,4.0,0.0

In [54]:
# replace Host_Build and Phantom_Build integer values with RAW_CAST, MELEE_PROC, RAW_PROC, RAW_MELEE, HYBRID
df['Phantom_Build'].replace([1.0, 2.0, 3.0, 4.0, 5.0] , ["RAW_CAST", "PROC_MELEE", "RAW_MELEE", "PROC_CAST", "HYBRID"], inplace=True)
df['Host_Build'].replace([1.0, 2.0, 3.0, 4.0, 5.0] , ["RAW_CAST", "PROC_MELEE", "RAW_MELEE", "PROC_CAST", "HYBRID"], inplace=True)

# replace locations with OUTER, INNER, CENTER
df['Location'].replace([1.0, 2.0, 3.0], ["OUTER", "INNER", "CENTER"], inplace=True)

#Replace Deaths 0 and 1 with True and False
df['Waterflow_Death'].replace([0.0, 1.0], [False, True], inplace=True)
df['Phantom_Death'].replace([0.0, 1.0], [False, True], inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [55]:
df.head(5)

,Host_Death_Time,Host_Build,Level,Phase,Waterflow_Death,Health_Pct,Location,Phantom_Count,Phantom_Build,Phantom_Death
0,147.0,HYBRID,149.0,1.0,True,25.0,OUTER,2.0,HYBRID,False
1,102.0,RAW_CAST,164.0,1.0,True,66.0,INNER,1.0,PROC_MELEE,True
2,81.0,RAW_MELEE,146.0,1.0,True,30.0,OUTER,2.0,PROC_MELEE,True
3,73.0,HYBRID,154.0,2.0,False,65.0,OUTER,1.0,HYBRID,True
4,141.0,PROC_CAST,146.0,1.0,True,6.0,OUTER,1.0,RAW_CAST,True

In [56]:
#Drop the rows where Phantom Death is 1 and Phantom Count is 1
df2 = df[(df['Phantom_Count'] == 1.0) & (df['Phantom_Death'] == False) ]
df = df[~df.index.isin(df2.index)]

In [57]:
#Where there is not another phantom, set Phantom_Build and Phantom_Death to NaN
df.loc[df['Phantom_Count'] == 1.0, 'Phantom_Build'] = np.nan
df.loc[df['Phantom_Count'] == 1.0, 'Phantom_Death'] = np.nan

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [58]:
df.head(25)

,Host_Death_Time,Host_Build,Level,Phase,Waterflow_Death,Health_Pct,Location,Phantom_Count,Phantom_Build,Phantom_Death
0,147.0,HYBRID,149.0,1.0,True,25.0,OUTER,2.0,HYBRID,False
1,102.0,RAW_CAST,164.0,1.0,True,66.0,INNER,1.0,NaN,NaN
2,81.0,RAW_MELEE,146.0,1.0,True,30.0,OUTER,2.0,PROC_MELEE,True
3,73.0,HYBRID,154.0,2.0,False,65.0,OUTER,1.0,NaN,NaN
4,141.0,PROC_CAST,146.0,1.0,True,6.0,OUTER,1.0,NaN,NaN
5,169.0,HYBRID,140.0,1.0,True,89.0,OUTER,2.0,RAW_CAST,False
6,292.0,RAW_CAST,159.0,1.0,True,62.0,INNER,2.0,PROC_MELEE,True
7,148.0,RAW_CAST,176.0,1.0,False,11.0,OUTER,1.0,NaN,NaN
8,193.0,HYBRID,177.0,2.0,True,29.0,CENTER,1.0,NaN,NaN
11,117.0,PROC_CAST,141.0,1.0,False,89.0,OUTER,2.0,HYBRID,False
12,283.0,PROC_CAST,154.0,1.0,False,14.0,OUTER,2.0,PROC_MELEE,False
13,95.0,PROC_MELEE,173.0,2.0,False,26.0,INNER,1.0,NaN,NaN
14,159.0,PROC_MELEE,150.0,2.0,False,43.0,OUTER,2.0,PROC_CAST,False
16,236.0,PROC_CAST,152.0,1.0,False,54.0,CENTER,2.0,RAW_CAST,True
19,156.0,RAW_CAST,164.0,2.0,False,53.0,CENTER,1.0,NaN,NaN
20,77.0,PROC_MELEE,151.0,1.0,True,55.0,CENTER,2.0,PROC_CAST,False
21,20.0,PROC_MELEE,151.0,2.0,False,76.0,OUTER,2.0,HYBRID,False
22,239.0,HYBRID,173.0,2.0,False,58.0,OUTER,2.0,HYBRID,False
23,48.0,RAW_MELEE,129.0,1.0,True,36.0,OUTER,1.0,NaN,NaN
25,157.0,PROC_CAST,150.0,1.0,True,32.0,OUTER,2.0,HYBRID,False
26,47.0,RAW_CAST,135.0,1.0,True,92.0,OUTER,1.0,NaN,NaN
27,162.0,RAW_CAST,138.0,2.0,False,20.0,INNER,2.0,PROC_CAST,False
28,171.0,HYBRID,140.0,2.0,False,81.0,CENTER,2.0,PROC_CAST,False
29,84.0,PROC_MELEE,167.0,1.0,True,71.0,INNER,2.0,HYBRID,True
30,95.0,RAW_CAST,157.0,2.0,False,21.0,OUTER,2.0,RAW_CAST,True

In [59]:
df.describe()

       Host_Death_Time        Level        Phase   Health_Pct  Phantom_Count
count      3575.000000  3575.000000  3575.000000  3575.000000    3575.000000
mean        163.601678   149.642238     1.509930    49.941259       1.650070
std          79.783136    17.866331     0.499971    25.637598       0.477014
min          10.000000   120.000000     1.000000     6.000000       1.000000
25%          94.000000   134.000000     1.000000    27.000000       1.000000
50%         166.000000   149.000000     2.000000    50.000000       2.000000
75%         233.000000   166.000000     2.000000    73.000000       2.000000
max         300.000000   180.000000     2.000000    93.000000       2.000000

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3575 entries, 0 to 4998
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Host_Death_Time  3575 non-null   float64
 1   Host_Build       3575 non-null   object
 2   Level            3575 non-null   float64
 3   Phase            3575 non-null   float64
 4   Waterflow_Death  3575 non-null   bool
 5   Health_Pct       3575 non-null   float64
 6   Location         3575 non-null   object
 7   Phantom_Count    3575 non-null   float64
 8   Phantom_Build    2324 non-null   object
 9   Phantom_Death    2324 non-null   object
dtypes: bool(1), float64(5), object(4)
memory usage: 282.8+ KB

--------------------------------------------------------------------------------